// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 ThetaCursed

#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod app;
mod color;
mod history;
mod lut;
mod lut_library;
mod pipeline;
mod presets;
mod session;
mod settings;
mod theme;
mod ui;

use std::sync::Arc;

use app::TinyLumaApp;
use eframe::egui;

/// Window (taskbar / Alt-Tab) icon, decoded from the PNG generated by
/// `examples/gen_icon.rs`. The `.exe` icon is embedded separately by `build.rs`.
fn app_icon() -> egui::viewport::IconData {
    let bytes = include_bytes!("../assets/icon_256.png");
    let image = image::load_from_memory(bytes)
        .expect("embedded app icon is a valid PNG")
        .to_rgba8();
    let (width, height) = image.dimensions();
    egui::viewport::IconData {
        rgba: image.into_raw(),
        width,
        height,
    }
}

fn main() -> eframe::Result {
    // The window is always borderless and transparent: we draw our own titlebar
    // (drag, minimize/maximize/close) and rounded corners — both in hero mode and
    // while editing. Opening an image maximizes the window.
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([ui::HERO_W, ui::HERO_H])
            .with_min_inner_size([ui::HERO_W, ui::HERO_H])
            .with_decorations(false)
            .with_transparent(true)
            .with_icon(Arc::new(app_icon())),
        ..Default::default()
    };
    // Full window title: name + tagline.
    let title = format!("{} — {}", ui::APP_NAME, ui::APP_TAGLINE);
    eframe::run_native(
        &title,
        options,
        Box::new(|cc| Ok(Box::new(TinyLumaApp::new(cc)))),
    )
}
